# Generated by Django 4.2.7 on 2026-06-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to='accounts.user'),
        ),
    ]
