# Generated by Django 4.2.7 on 2026-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='nida_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
